version: 0.2

phases:

  install:
    runtime_versions:
      nodejs: 12

  build:
    commands:
      - cd ${CODEBUILD_SRC_DIR}
      - npm install
      - npm run build
artifacts:
  base-directory: ${CODEBUILD_SRC_DIR}
  files:
    - '**/*'
